### PR TITLE
Integrate bsdl2json

### PR DESCRIPTION
**Pull request by raczben**
I have created [bsdl-parser](https://pypi.org/project/bsdl-parser/) package. I have integrated it to this project. Now you can give bsdl files directly to bsdl-parser

### CODE REVIEW

**Comment by tomverbeure** [comment]
Very nice! Thanks!

**Comment by tomverbeure** [comment]
Hey Bendek,

I blindly accepted your pull request without testing it, but I'm now trying it on a new machine and even after doing the 'pip install' of bsdl-parser, I get the following error:

```
./bscan_proc.py EP1AGX90EF1152.BSD example/bscan_values.txt 
INFO:root:EP1AGX90EF1152.BSD is not a json file... Lets's find in the cache
INFO:root:/home/tom/.cache/bscan_proc/EP1AGX90EF1152.BSD.json not found in cache... Lets's parse original.
INFO:root:bsdl2json EP1AGX90EF1152.BSD -o /home/tom/.cache/bscan_proc/EP1AGX90EF1152.BSD.json From: '../python-bsdl-parser'
Traceback (most recent call last):
  File "./bscan_proc.py", line 55, in <module>
    data = json.load(json_file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bscan_proc.py", line 73, in <module>
    p = subprocess.Popen(cmdlist, cwd='../python-bsdl-parser')
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '../python-bsdl-parser'
```

On this new machine, `../python-bsdl-parser` doesn't exist, but I assume that wouldn't have been necessary because you required that bsdl-parser package?

What's the right way to go forward on this?

Tom

**Comment by tomverbeure** [comment]
The following commit fixes things for me: cf8d5f401c82fabca59b19144496a63fb3912e68.

Does that look reasonable to you?

Tom

**Comment by raczben** [comment]
Sorry, for the delay. I was busy.

Thanks for the fix. I want to add further features to improove user experience.

**Pull request merged**
